version: '3.9'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - '5000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: backend
    build: ./api/
    ports:
      - '5001:5000'
  redis:
    container_name: redis
    image: 'redis:alpine'
